### ISSUE TITLE
Let cache control directives work on interfaces

### ISSUE THREAD

**Issue by adolfosbh** [apollographql/apollo-cache-control-js#11]
When I use interfaces in my schema,
,and I have a query that returns such an interfaces,
cache hints are never included in the response.

There are many use cases scenario when dealing with interface. 

This issue covers the simple scenario that makes the implementation properly include the cache control hints in the response (when the cache control directives are declared on interfaces)

**Comment by adolfosbh** [comment]
Pull Request -> #10

**Comment by evans** [comment]
@adolfosbh thank you so much for the issue and PR. With #10 included, it should be solved. The extension has been moved to https://github.com/apollographql/apollo-server/, so if you have any more feature requests, please open an issue there https://github.com/apollographql/apollo-server/issues/new

The PR moving it over is https://github.com/apollographql/apollo-server/pull/1294. I did have to remove one of instanceof checks, since the new graphql types indicated that `info.parentType` could not be a GraphQLInterfaceType
