### ISSUE TITLE
__tests__/cacheControlDirective.ts empty after compilation

### ISSUE THREAD

**Issue by luandro** [apollographql/apollo-cache-control-js#25]
For some reason the [/__tests__/cacheControlDirective.ts](https://github.com/apollographql/apollo-cache-control-js/blob/master/src/__tests__/cacheControlDirective.ts) file is empty after being compiled, and that's crashing my [nodejs-mobile](https://github.com/janeasystems/nodejs-mobile) app running on React Native.

**Comment by evans** [comment]
I'm going to close this issue, since we moved the extension over to https://github.com/apollographql/apollo-server/. 

I'm not sure the cause of the issue, since compilation should not remove files. If the error persists and compilation continues to fail, please open an issue https://github.com/apollographql/apollo-server/issues/new
