### ISSUE TITLE
Questions and clarifications about caching strategies

### ISSUE THREAD

**Issue by emmenko** [apollographql/apollo-cache-control-js#4]
Hey guys,

thanks a lot for those amazing new features that you are working on ❤️ 🙌 

I was trying out the `cache` feature and I had some questions:

#### Cache `PRIVATE` scope
The doc says:

> If scope is set to `PRIVATE`, that indicates anything under this path should only be cached per-user, unless the value is overridden on a subpath.

What exactly does it mean `per-user`? I mean, what is the logic that determines "which user" is it? I tried to look at the source code but couldn't find out the related logic.

#### Cache hits
I added a cache directive to one of my types and I can see the "cacheControl hints" in the graphql response. I can also see it in Apollo Engine

![image](https://user-images.githubusercontent.com/1110551/32095658-2bfa2f48-bb04-11e7-8ad7-e68f2ee82228.png)

However the metric for the _cache hits_ is still `0`.
I'm not sure if I've missed something or simply I don't fully understand how the cache really works.
I also tried to run the engine with log level `DEBUG` but couldn't see any useful log related to the cache.

#### Cache invalidation
@mxstbr already asked about this :) #1 

#### Cache strategy on fields with parameters
What is the strategy for caching and for invalidating the cache for field parameters?
For example, in the doc you showed this schema:

```js
type Post @cacheControl(maxAge: 240) {
  id: Int!
  title: String
  author: Author
  votes: Int @cacheControl(maxAge: 30)
  readByCurrentUser: Boolean! @cacheControl(scope: PRIVATE)
}
```

and the following query:

```js
query {
  post(id: 1) {
    title
    votes
    readByCurrentUser
  }
}
```

So the cache is defined on the `Post` type, however you query the post by `id`. So what happens if I trigger the following queries?

```js
post(id: 1) // first hit, return normal result
post(id: 1) // second hit, return from the cache?
post(id: 2) // what happens here? I assume that I will get a fresh result because the id changed
post(id: 1) // what about here? do you get it from the cache or has it been invalidated because of the previous query with id: 2?
```

---
I would appreciate any clarifying feedback 🙏
Thanks a lot!

**Comment by martijnwalraven** [comment]
Those are some great questions!

- The logic that determines the current user is not part of the spec or of this implementation. If a path has been marked as `PRIVATE`, that means it should not be stored in a cache that is shared between users. For Engine, there is a `sessionAuth` field in the proxy config that you can use to specify which header should be used to differentiate between users (you would normally set this to `Authorization` for example).

- If you don't see cache hits, that usually means there is a path in your response that has `maxAge: 0` set. That happens for all objects that do not have an explicit `@cacheControl` defined, because caching is opt-in. You should be able to see that if you expand the fields under the 'cache' tab.

- Cache control hints define which parts of the response can be cached, but they don't define how these will be cached. So all `type Post @cacheControl(maxAge: 240)` means is that if my response includes a post, it can only be cached for a maximum of 240 seconds. 
Engine always  caches the whole response, and it uses the query signature + variable values as a cache key.  So either `post(id: 1)` and `post(id: 2)` are different queries, or the query would be `post(id: $postId)` and the variable values would be different.

(Sorry for the late response, but I got bitten by the fact that creating a repo doesn't automatically make you watch it.)

**Comment by evans** [comment]
I'm going to close this, since we moved the repo over to https://github.com/apollographql/apollo-server. If you have any other questions, please feel free to open an issue https://github.com/apollographql/apollo-server/issues/new.

We'll aim to add the information from this thread into the documentation for as2

apollographql/apollo-server#1294 for reference
